// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function CloseWindow():Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteSmartFolder(arg1:string):Promise<void>;

export function GetDatabasePath():Promise<string>;

export function GetSyncConfiguration():Promise<main.SyncConfiguration>;

export function GetSyncProfileID():Promise<string>;

export function IsWindowMaximized():Promise<boolean>;

export function ListDeletedNotes():Promise<Array<main.Note>>;

export function ListNavigation():Promise<main.Navigation>;

export function ListNotes():Promise<Array<main.Note>>;

export function MinimizeWindow():Promise<void>;

export function MoveNote(arg1:string,arg2:string):Promise<void>;

export function QueryNotes(arg1:main.NoteQuery):Promise<Array<main.Note>>;

export function RestoreNote(arg1:string):Promise<void>;

export function SaveFolder(arg1:main.Folder):Promise<main.Folder>;

export function SaveNote(arg1:main.Note):Promise<main.Note>;

export function SaveSmartFolder(arg1:main.SmartFolder):Promise<main.SmartFolder>;

export function SaveSyncConfiguration(arg1:string,arg2:string):Promise<main.SyncConfiguration>;

export function SetCustomDatabasePath(arg1:string):Promise<string>;

export function SetNotePinned(arg1:string,arg2:boolean):Promise<main.Note>;

export function SetNoteTags(arg1:string,arg2:Array<string>):Promise<main.Note>;

export function SetSyncProfileID(arg1:string):Promise<void>;

export function SyncNow(arg1:string):Promise<main.SyncResult>;

export function ToggleMaximizeWindow():Promise<boolean>;
