// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CreateDatabaseBackup() {
  return window['go']['main']['App']['CreateDatabaseBackup']();
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteSmartFolder(arg1) {
  return window['go']['main']['App']['DeleteSmartFolder'](arg1);
}

export function DeleteSticker(arg1) {
  return window['go']['main']['App']['DeleteSticker'](arg1);
}

export function DeleteStickerBoard(arg1) {
  return window['go']['main']['App']['DeleteStickerBoard'](arg1);
}

export function DeleteSubtask(arg1) {
  return window['go']['main']['App']['DeleteSubtask'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTaskList(arg1) {
  return window['go']['main']['App']['DeleteTaskList'](arg1);
}

export function EmptyDeletedNotes() {
  return window['go']['main']['App']['EmptyDeletedNotes']();
}

export function ExportNoteFile(arg1, arg2) {
  return window['go']['main']['App']['ExportNoteFile'](arg1, arg2);
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetSyncConfiguration() {
  return window['go']['main']['App']['GetSyncConfiguration']();
}

export function GetSyncDiagnosticReport() {
  return window['go']['main']['App']['GetSyncDiagnosticReport']();
}

export function GetSyncProfileID() {
  return window['go']['main']['App']['GetSyncProfileID']();
}

export function GetSyncProfileInfo() {
  return window['go']['main']['App']['GetSyncProfileInfo']();
}

export function GetTaskWithSubtasks(arg1) {
  return window['go']['main']['App']['GetTaskWithSubtasks'](arg1);
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function ListDeletedNotes() {
  return window['go']['main']['App']['ListDeletedNotes']();
}

export function ListNavigation() {
  return window['go']['main']['App']['ListNavigation']();
}

export function ListNoteConflicts() {
  return window['go']['main']['App']['ListNoteConflicts']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function ListRemoteSyncProfiles() {
  return window['go']['main']['App']['ListRemoteSyncProfiles']();
}

export function ListStickers(arg1) {
  return window['go']['main']['App']['ListStickers'](arg1);
}

export function ListTaskLists() {
  return window['go']['main']['App']['ListTaskLists']();
}

export function ListTasks(arg1, arg2) {
  return window['go']['main']['App']['ListTasks'](arg1, arg2);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function MoveSticker(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveSticker'](arg1, arg2, arg3);
}

export function PermanentlyDeleteNote(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteNote'](arg1);
}

export function PurgeRemoteSyncProfile(arg1) {
  return window['go']['main']['App']['PurgeRemoteSyncProfile'](arg1);
}

export function QueryNotes(arg1) {
  return window['go']['main']['App']['QueryNotes'](arg1);
}

export function ResolveNoteConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveNoteConflict'](arg1, arg2);
}

export function RestoreDatabaseBackup() {
  return window['go']['main']['App']['RestoreDatabaseBackup']();
}

export function RestoreFromCloud() {
  return window['go']['main']['App']['RestoreFromCloud']();
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function RestoreSticker(arg1) {
  return window['go']['main']['App']['RestoreSticker'](arg1);
}

export function RunComplianceAudit() {
  return window['go']['main']['App']['RunComplianceAudit']();
}

export function SaveAutoSyncInterval(arg1) {
  return window['go']['main']['App']['SaveAutoSyncInterval'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['main']['App']['SaveFolder'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SaveSmartFolder(arg1) {
  return window['go']['main']['App']['SaveSmartFolder'](arg1);
}

export function SaveSticker(arg1) {
  return window['go']['main']['App']['SaveSticker'](arg1);
}

export function SaveStickerBoard(arg1) {
  return window['go']['main']['App']['SaveStickerBoard'](arg1);
}

export function SaveSubtask(arg1) {
  return window['go']['main']['App']['SaveSubtask'](arg1);
}

export function SaveSyncConfiguration(arg1, arg2) {
  return window['go']['main']['App']['SaveSyncConfiguration'](arg1, arg2);
}

export function SaveTag(arg1) {
  return window['go']['main']['App']['SaveTag'](arg1);
}

export function SaveTask(arg1) {
  return window['go']['main']['App']['SaveTask'](arg1);
}

export function SaveTaskList(arg1) {
  return window['go']['main']['App']['SaveTaskList'](arg1);
}

export function SetCustomDatabasePath(arg1) {
  return window['go']['main']['App']['SetCustomDatabasePath'](arg1);
}

export function SetNotePinned(arg1, arg2) {
  return window['go']['main']['App']['SetNotePinned'](arg1, arg2);
}

export function SetNoteTags(arg1, arg2) {
  return window['go']['main']['App']['SetNoteTags'](arg1, arg2);
}

export function SetPrimarySyncProfile(arg1) {
  return window['go']['main']['App']['SetPrimarySyncProfile'](arg1);
}

export function SetStickerPinned(arg1, arg2) {
  return window['go']['main']['App']['SetStickerPinned'](arg1, arg2);
}

export function SetSyncProfileID(arg1) {
  return window['go']['main']['App']['SetSyncProfileID'](arg1);
}

export function SyncNow(arg1) {
  return window['go']['main']['App']['SyncNow'](arg1);
}

export function TestTursoConnection(arg1, arg2) {
  return window['go']['main']['App']['TestTursoConnection'](arg1, arg2);
}

export function ToggleMaximizeWindow() {
  return window['go']['main']['App']['ToggleMaximizeWindow']();
}

export function ToggleSubtaskCompleted(arg1, arg2) {
  return window['go']['main']['App']['ToggleSubtaskCompleted'](arg1, arg2);
}

export function ToggleTaskCompleted(arg1, arg2) {
  return window['go']['main']['App']['ToggleTaskCompleted'](arg1, arg2);
}
