// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteSmartFolder(arg1) {
  return window['go']['main']['App']['DeleteSmartFolder'](arg1);
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function ListDeletedNotes() {
  return window['go']['main']['App']['ListDeletedNotes']();
}

export function ListNavigation() {
  return window['go']['main']['App']['ListNavigation']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function QueryNotes(arg1) {
  return window['go']['main']['App']['QueryNotes'](arg1);
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['main']['App']['SaveFolder'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SaveSmartFolder(arg1) {
  return window['go']['main']['App']['SaveSmartFolder'](arg1);
}

export function SetCustomDatabasePath(arg1) {
  return window['go']['main']['App']['SetCustomDatabasePath'](arg1);
}

export function SetNotePinned(arg1, arg2) {
  return window['go']['main']['App']['SetNotePinned'](arg1, arg2);
}

export function SetNoteTags(arg1, arg2) {
  return window['go']['main']['App']['SetNoteTags'](arg1, arg2);
}

export function ToggleMaximizeWindow() {
  return window['go']['main']['App']['ToggleMaximizeWindow']();
}
